version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=admin12345
    deploy:
      replicas: 1

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin12345
      MINIO_DEFAULT_BUCKETS: dam-assets
    command: server /data --console-address ":9001"
    deploy:
      replicas: 1

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: dam_platform
    deploy:
      replicas: 1

  asset-worker:
    image: dam-platform-asset-worker
    restart: always
    depends_on:
      - redis
      - minio
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/dam_platform
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin12345
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=admin12345
    volumes:
      - /tmp:/tmp
    deploy:
      replicas: 1
      labels:
        - "swarm.autoscaler=true"
      resources:
        reservations:
          cpus: '0.25'
          memory: 256M
        limits:
          cpus: '0.5'
          memory: 512M

  backend:
    image: dam-platform-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - minio
      - redis
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/dam_platform
      - PORT=5000
      - MINIO_ENDPOINT=minio
      - ACCESS_TOKEN_EXPIRY=1d
      - ACCESS_TOKEN_SECRET=1234
      - CORS_ORIGIN=http://localhost:5173,http://localhost:3000
      - MINIO_PORT=9000
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin12345
      - MINIO_DEFAULT_BUCKETS=dam-assets
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=admin12345
    deploy:
      replicas: 1
      labels:
        - "swarm.autoscaler=true"
      resources:
        reservations:
          cpus: '0.25'
          memory: 256M
        limits:
          cpus: '0.5'
          memory: 512M

  frontend:
    image: dam-platform-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    deploy:
      replicas: 1

    volumes:
  mongodb_data:
    driver: local
