version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: dam-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dam-network

  backend:
    build: ./backend
    container_name: backend_container
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/dam_platform
      - PORT=5000
      - ACCESS_TOKEN_EXPIRY=1d
      - ACCESS_TOKEN_SECRET=1234
      - CORS_ORIGIN=http://localhost:5173
      
  frontend:
    build: ./frontend
    container_name: frontend_container
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: dam_platform

volumes:
  mongodb_data:
    driver: local