apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: alokraj889/backend-dam:0.5
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
        envFrom:
          - configMapRef:
              name: backend-config
        name: backend
        resources: 
          requests:
              cpu: "500m"
              memory: "512Mi"
          limits:
              cpu: "1"
              memory: "1Gi"
status: {}
